# Build customization
builds:
  - binary: manssh
    main: ./cmd/manssh/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: xwjdsh
    name: homebrew-tap

  commit_author:
    name: Wendell Sun
    email: iwendellsun@gmail.com

  homepage: "https://github.com/xwjdsh/manssh"
  description: "Manage your ssh alias configs easily"

  install: |
    bin.install "manssh"

release:
  github:
    owner: xwjdsh
    name: manssh
